### ISSUE TITLE
Supply Docker dependencies without their version

### ISSUE THREAD

**Issue by Krijger** [Krijger/docker-gradle#48]
Currently, updating a dependency version also results in a change in the Dockerfile. This can be avoided. On the assumption that symlinks are followed on a COPY statement, the collectImageDependencies task can create a symlink to the dependency without the version.

E.g.

```
dependencies {
  docker group: 'nl.qkrijger.gradle', name: 'fake', version: '0.1-FAKE', ext: 'txt'
}
```

would result in 

```
build/docker-deps/
|-- fake-0.1-FAKE.txt
|-- fake.txt    (symlink to above file)  
```

so the Dockerfile can simply

```
COPY build/docker-deps/fake.txt /my-file.txt
```

**Comment by wouterd** [comment]
Check how i did this in the ffw docker projects. :)

**Comment by Krijger** [comment]
Sure,

```
def filename = it.name + (it.classifier ? '-' + it.classifier : '') + '.' + it.extension
```

is fine logic for the name. And indeed, no need of a symlink... Copying a code fragment here for reference

```
(type: Copy) { copy ->
  configurations.dockerArtifacts.resolvedConfiguration.resolvedArtifacts.each {
    from it.file
    into file('build/docker-deps')
    def filename = it.name + (it.classifier ? '-' + it.classifier : '') + '.' + it.extension
    println "Preparing build/docker-artifacts/${filename}"
    rename it.file.name, filename
  }
}
```

@wouterd did you notive how clean the current task is? Would be nice if we can avoid the `each`

```
CollectImageDependenciesTask() {
  description = 'Copies the Docker dependencies to the build folder to make them available during an image build'
  group = 'Docker'

  from project.configurations.docker
  into "${project.buildDir}/docker-deps"
}
```

**Comment by wouterd** [comment]
Pretty sure I tried that, but the rename gets a target file name, not an
artifact. So you'd have to "voodoo up" the filename with some regexing..

**Comment by Krijger** [comment]
@wouterd What about keeping the dependency as is (with version) in the build/stackwork-deps directory (so no change here), but adding a symlink without version next to it?
