### ISSUE TITLE
Add plugin to to Gradle plugin portal

### ISSUE THREAD

**Issue by ysb33r** [Krijger/docker-gradle#56]
It would be good if this is pushed to the central Gradle plugin portal as well.

It will need a change in the plugin name to be fully qualified, maybe `io.stackworks.docker`.

it will also need addition of the plugin-publish-plugin, See https://plugins.gradle.org/docs/submit for details.

**Comment by Krijger** [comment]
Thanks for your comment.

Stackwork.org has now been registered, so a good name is `org.stackwork`.

I need to look at how to encrypt the API key for use with Travis and the plugin-publish-plugin.

**Comment by Krijger** [comment]
@ysb33r , I have added this publishing and created a release candidate to test the publishing (because I setup Travis to only publish releases and release candidates). Please check the result of

```
Publishing plugin org.stackwork.gradle version 0.6.0-rc.4
```

**Comment by ysb33r** [comment]
Cool, I'll give it a go. 

Just one point is that we do not normally include `gradle` in the ID of the plugin. It is fine to have `gradle` in the package, but not the ID. If you think about it, veerything on the portal is is already a Gradle plugin, therefore adding it to the ID is just superfluous.

**Comment by Krijger** [comment]
I agree. Here you go: https://plugins.gradle.org/plugin/org.stackwork
Closing this issue. If something is wrong you know where to find me :)
